interface Product {
  order_number: number;
  customer_name: string;
  product_name: string;
  product_category: string;
  price: number;
  order_date: string;
}

const PRODUCT: Product[] = [
  {
    order_number: 1,
    customer_name: "Lucien Caplan",
    product_name: "New Barbarians, The (I nuovi barbari)",
    product_category: "Drama",
    price: 14902,
    order_date: "21/07/2020",
  },
  {
    order_number: 2,
    customer_name: "Abbi Ravens",
    product_name: "Towelhead (a.k.a. Nothing is Private)",
    product_category: "Drama",
    price: 16121,
    order_date: "27/04/2022",
  },
  {
    order_number: 3,
    customer_name: "Christine Hain",
    product_name: "Head On",
    product_category: "Drama",
    price: 8298,
    order_date: "08/09/2021",
  },
  {
    order_number: 4,
    customer_name: "Kathryne Mouse",
    product_name:
      "RKO Production 601: The Making of 'Kong, the Eighth Wonder of the World'",
    product_category: "Comedy",
    price: 10295,
    order_date: "10/12/2021",
  },
  {
    order_number: 5,
    customer_name: "Andria Mordanti",
    product_name: "BloodRayne",
    product_category: "Comedy",
    price: 17035,
    order_date: "11/11/2021",
  },
  {
    order_number: 6,
    customer_name: "Birch Manson",
    product_name: "Boys on the Side",
    product_category: "Drama",
    price: 3700,
    order_date: "09/11/2022",
  },
  {
    order_number: 7,
    customer_name: "Robinia Colthard",
    product_name: "Chouga (Shuga)",
    product_category: "Drama",
    price: 10579,
    order_date: "23/07/2020",
  },
  {
    order_number: 8,
    customer_name: "Magdalena Amsden",
    product_name: "Sapphires, The",
    product_category: "Comedy",
    price: 9025,
    order_date: "17/03/2022",
  },
  {
    order_number: 9,
    customer_name: "Mathe Struijs",
    product_name: "House",
    product_category: "Comedy",
    price: 9270,
    order_date: "05/11/2021",
  },
  {
    order_number: 10,
    customer_name: "Kip Libbe",
    product_name: "American Dreams in China",
    product_category: "Documentary",
    price: 17917,
    order_date: "16/01/2022",
  },
  {
    order_number: 11,
    customer_name: "Nelie Pexton",
    product_name: "Frankenstein Conquers the World",
    product_category: "Sci-Fi",
    price: 11284,
    order_date: "08/07/2023",
  },
  {
    order_number: 12,
    customer_name: "Noe Trench",
    product_name: "Broadcast News",
    product_category: "Sci-Fi",
    price: 2244,
    order_date: "21/01/2021",
  },
  {
    order_number: 13,
    customer_name: "Chic Comber",
    product_name: "Star Wars Uncut: Director's Cut",
    product_category: "Sci-Fi",
    price: 12653,
    order_date: "27/09/2020",
  },
  {
    order_number: 14,
    customer_name: "Ceil Tharme",
    product_name: "The Losers",
    product_category: "Documentary",
    price: 7550,
    order_date: "10/05/2022",
  },
  {
    order_number: 15,
    customer_name: "Maggi Nicklen",
    product_name: "Stars Fell on Henrietta, The",
    product_category: "Drama",
    price: 13389,
    order_date: "30/06/2021",
  },
  {
    order_number: 16,
    customer_name: "Leah Coston",
    product_name: "Battle of amfAR, The",
    product_category: "Drama",
    price: 7611,
    order_date: "01/01/2021",
  },
  {
    order_number: 17,
    customer_name: "Arielle Egentan",
    product_name: "Doomsday Prophecy",
    product_category: "Drama",
    price: 1728,
    order_date: "02/09/2022",
  },
  {
    order_number: 18,
    customer_name: "Virginia Pledge",
    product_name: "Human Traffic",
    product_category: "Comedy",
    price: 2148,
    order_date: "04/05/2021",
  },
  {
    order_number: 19,
    customer_name: "Kari Akess",
    product_name: "End of the Line",
    product_category: "Horror",
    price: 10435,
    order_date: "06/09/2020",
  },
  {
    order_number: 20,
    customer_name: "Arin Keld",
    product_name: "Friday the 13th",
    product_category: "Horror",
    price: 2060,
    order_date: "14/12/2020",
  },
  {
    order_number: 21,
    customer_name: "Valdemar Scotchmer",
    product_name: "Fruitcake",
    product_category: "Horror",
    price: 9586,
    order_date: "30/12/2022",
  },
  {
    order_number: 22,
    customer_name: "Hewitt Philipard",
    product_name: "Waterloo",
    product_category: "Documentary",
    price: 16636,
    order_date: "30/01/2023",
  },
  {
    order_number: 23,
    customer_name: "Fidelio Chart",
    product_name: "Our Little Differences (Die feinen Unterschiede)",
    product_category: "Documentary",
    price: 16337,
    order_date: "12/05/2022",
  },
  {
    order_number: 24,
    customer_name: "Rourke MacRannell",
    product_name: "My Bollywood Bride",
    product_category: "Horror",
    price: 7067,
    order_date: "02/01/2022",
  },
  {
    order_number: 25,
    customer_name: "Tani Watkins",
    product_name: "My Forbidden Past",
    product_category: "Horror",
    price: 4853,
    order_date: "17/01/2023",
  },
  {
    order_number: 26,
    customer_name: "Rutter Knoles",
    product_name: "Any Wednesday (Bachelor Girl Apartment)",
    product_category: "Comedy",
    price: 3982,
    order_date: "27/08/2022",
  },
  {
    order_number: 27,
    customer_name: "Basilius Guise",
    product_name: "Cousin Angelica (La prima Angélica)",
    product_category: "Drama",
    price: 11156,
    order_date: "11/04/2020",
  },
  {
    order_number: 28,
    customer_name: "Manfred O'Lochan",
    product_name: "Unfaithful, The",
    product_category: "Drama",
    price: 7431,
    order_date: "14/09/2022",
  },
  {
    order_number: 29,
    customer_name: "Annabela Hammerich",
    product_name: "Dragon Missile, The (Fei long zhan)",
    product_category: "Drama",
    price: 12758,
    order_date: "09/03/2022",
  },
  {
    order_number: 30,
    customer_name: "Margit Cabral",
    product_name: "Magnificent Seven Ride!, The",
    product_category: "Drama",
    price: 4025,
    order_date: "19/12/2020",
  },
  {
    order_number: 31,
    customer_name: "Joleen Kitchenside",
    product_name: "Jericho Mile, The",
    product_category: "Documentary",
    price: 16312,
    order_date: "04/10/2020",
  },
  {
    order_number: 32,
    customer_name: "Ailbert Iremonger",
    product_name: "Kilometre Zero (Kilomètre zéro)",
    product_category: "Documentary",
    price: 2151,
    order_date: "08/08/2023",
  },
  {
    order_number: 33,
    customer_name: "Gertruda Crilley",
    product_name: "Around the World in 80 Days",
    product_category: "Horror",
    price: 16747,
    order_date: "20/12/2020",
  },
  {
    order_number: 34,
    customer_name: "Kayley Bellhouse",
    product_name: "Trans-Atlantic Tunnel (Tunnel, The)",
    product_category: "Horror",
    price: 3366,
    order_date: "30/09/2021",
  },
  {
    order_number: 35,
    customer_name: "Ola Esler",
    product_name: "Evidence of Blood",
    product_category: "Documentary",
    price: 8758,
    order_date: "16/08/2020",
  },
  {
    order_number: 36,
    customer_name: "Emmit O'Tierney",
    product_name: "Song of Sparrows, The (Avaze gonjeshk-ha)",
    product_category: "Documentary",
    price: 11170,
    order_date: "11/01/2022",
  },
  {
    order_number: 37,
    customer_name: "Adolph Bark",
    product_name: "Kanak Attack",
    product_category: "Drama",
    price: 17885,
    order_date: "30/12/2021",
  },
  {
    order_number: 38,
    customer_name: "Cleopatra MacKimmie",
    product_name: "Monster in Paris, A (Un monstre à Paris)",
    product_category: "Sci-Fi",
    price: 10290,
    order_date: "19/09/2020",
  },
  {
    order_number: 39,
    customer_name: "Emlynn Stambridge",
    product_name: "Cry Baby Lane",
    product_category: "Drama|Horror",
    price: 8312,
    order_date: "04/02/2020",
  },
  {
    order_number: 40,
    customer_name: "Georgeanne Howkins",
    product_name: "Fingersmith",
    product_category: "Horror",
    price: 13961,
    order_date: "13/04/2021",
  },
  {
    order_number: 41,
    customer_name: "Kore Ivanovic",
    product_name: "Strange Circus (Kimyô na sâkasu)",
    product_category: "Horror",
    price: 13257,
    order_date: "11/12/2020",
  },
  {
    order_number: 42,
    customer_name: "Stevie Dunsford",
    product_name: "Army of One (Joshua Tree)",
    product_category: "Documentary",
    price: 10376,
    order_date: "11/04/2020",
  },
  {
    order_number: 43,
    customer_name: "Cully Shearmur",
    product_name: "Monster That Challenged the World, The",
    product_category: "Documentary",
    price: 15694,
    order_date: "11/11/2022",
  },
  {
    order_number: 44,
    customer_name: "Aurora Odeson",
    product_name: "Tabu",
    product_category: "Comedy",
    price: 8019,
    order_date: "01/10/2020",
  },
  {
    order_number: 45,
    customer_name: "Matteo Soper",
    product_name: "7 Seconds",
    product_category: "Comedy",
    price: 16958,
    order_date: "16/05/2022",
  },
  {
    order_number: 46,
    customer_name: "Shannon Farnan",
    product_name: "IMAX: Coral Reef Adventure",
    product_category: "Comedy",
    price: 6618,
    order_date: "26/01/2023",
  },
  {
    order_number: 47,
    customer_name: "Myrlene Kinahan",
    product_name: "Possession of David O'Reilly, The",
    product_category: "Horror",
    price: 13876,
    order_date: "12/07/2022",
  },
  {
    order_number: 48,
    customer_name: "Freda Cowley",
    product_name: "Midnight (Primeiro Dia, O)",
    product_category: "Drama",
    price: 1071,
    order_date: "10/12/2021",
  },
  {
    order_number: 49,
    customer_name: "Melitta Grigsby",
    product_name: "Listen to Britain",
    product_category: "Horror",
    price: 6130,
    order_date: "08/10/2020",
  },
  {
    order_number: 50,
    customer_name: "Licha Lambricht",
    product_name: "Bridge on the River Kwai, The",
    product_category: "Horror",
    price: 9315,
    order_date: "17/11/2020",
  },
];
